DROP TABLE IF EXISTS STUDENTS;
DROP TABLE IF EXISTS QUIZZES;
DROP TABLE IF EXISTS RESULTS;

CREATE TABLE STUDENTS
(
ID INTEGER PRIMARY KEY NOT NULL,
FIRST_NAME TEXT NOT NULL,
LAST_NAME TEXT NOT NULL
);

CREATE TABLE QUIZZES
(
ID INTEGER PRIMARY KEY NOT NULL,
SUBJECT TEXT,
QUESTION_COUNT INTEGER,
QUIZ_DATE TEXT
);

CREATE TABLE RESULTS
(
STUDENT_ID INTEGER NOT NULL,
QUIZ_ID INTEGER NOT NULL,
SCORE INTEGER NOT NULL
);

INSERT INTO STUDENTS (ID, FIRSTNAME, LASTNAME) values (01, "John", "Smith");
INSERT INTO QUIZZES (ID, SUBJECT, QUESTION_COUNT, QUIZ_DATE) values (01, "Python Basics", 5, "February, 5th, 2015");
INSERT INTO RESULTS (STUDENTID, QUIZID, SCORE) values (01,01,85);
